name: docusaurus-plugin-ts2esm2cjs
org: sapphire
install: true
packagePath: packages/ts2esm2cjs
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
gitRepo: sapphiredev/documentation-plugins
gitHostVariant: github
