name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linting:
    name: Linting
    uses: sapphiredev/.github/.github/workflows/reusable-lint.yml@main

  build:
    name: Building
    uses: sapphiredev/.github/.github/workflows/reusable-build.yml@main

  test:
    name: Tests
    uses: sapphiredev/.github/.github/workflows/reusable-tests.yml@main
    with:
      enable-sonar: true
    secrets:
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  typecheck:
    name: Typecheck node v${{ matrix.node }}
    strategy:
      fail-fast: false
      matrix:
        node: [18, 19, 20, 21, 22]
    uses: sapphiredev/.github/.github/workflows/reusable-typecheck.yml@main
    with:
      node-version: ${{ matrix.node }}
