name: Publish

on:
  workflow_dispatch:
    inputs:
      package:
        description: The package to release, this should be the path segment after packages/, without the @sapphire/ prefix
        required: true

jobs:
  PublishPackage:
    name: Publish @sapphire/framework
    uses: sapphiredev/.github/.github/workflows/reusable-publish.yml@main
    with:
      project-name: '@sapphire/${{ github.event.inputs.package}}'
      working-directory: packages/${{ github.event.inputs.package }}
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      SKYRA_TOKEN: ${{ secrets.SKYRA_TOKEN }}
