name: Publish
run-name: Publish ${{ inputs.package }}

on:
  workflow_dispatch:
    inputs:
      package:
        description: The package to release, this should be the path segment after packages/, without the prefix
        required: true
      skip-automatic-bump:
        description: Whether to skip the automatic bumping of the packageversion
        required: false
        default: false
        type: boolean

jobs:
  PublishPackage:
    name: Publish ${{ inputs.package}}
    uses: sapphiredev/.github/.github/workflows/reusable-publish.yml@main
    with:
      project-name: ${{ inputs.package}}
      working-directory: packages/${{ inputs.package }}
      skip-automatic-bump: ${{ inputs.skip-automatic-bump }}
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      SKYRA_TOKEN: ${{ secrets.SKYRA_TOKEN }}
